
package com.pharos.credibanco.checkout.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.pharos.credibanco.checkout.ws.Audit;
import com.pharos.credibanco.checkout.ws.BinesRange;
import com.pharos.credibanco.checkout.ws.Certificates;
import com.pharos.credibanco.checkout.ws.Exception_Exception;
import com.pharos.credibanco.checkout.ws.Faq;
import com.pharos.credibanco.checkout.ws.ObjectFactory;
import com.pharos.credibanco.checkout.ws.Parameter;
import com.pharos.credibanco.checkout.ws.PosPago;
import com.pharos.credibanco.checkout.ws.Response;
import com.pharos.credibanco.checkout.ws.ResponseRestore;
import com.pharos.credibanco.checkout.ws.RestoreSession;
import com.pharos.credibanco.checkout.ws.User;
import com.pharos.credibanco.checkout.ws.UserCard;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckoutWSService", targetNamespace = "http://ws.checkout.credibanco.pharos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckoutWSService {


    /**
     * 
     * @param commerceCode
     * @param terminalCode
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCommerce", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCommerce")
    @ResponseWrapper(localName = "deleteCommerceResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCommerceResponse")
    public Response deleteCommerce(
        @WebParam(name = "commerceCode", targetNamespace = "")
        String commerceCode,
        @WebParam(name = "terminalCode", targetNamespace = "")
        String terminalCode);

    /**
     * 
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "updateRegisterDate", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateRegisterDate")
    @ResponseWrapper(localName = "updateRegisterDateResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateRegisterDateResponse")
    public void updateRegisterDate(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.ResponseRestore
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restorePassword", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.RestorePassword")
    @ResponseWrapper(localName = "restorePasswordResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.RestorePasswordResponse")
    public ResponseRestore restorePassword(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @return
     *     returns java.util.List<com.pharos.credibanco.checkout.ws.Certificates>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCertificates", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.FindAllCertificates")
    @ResponseWrapper(localName = "findAllCertificatesResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.FindAllCertificatesResponse")
    public List<Certificates> findAllCertificates()
        throws Exception_Exception
    ;

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "sendCreateEmail", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendCreateEmail")
    @ResponseWrapper(localName = "sendCreateEmailResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendCreateEmailResponse")
    public void sendCreateEmail(
        @WebParam(name = "User", targetNamespace = "")
        User user);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "editCertificate", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.EditCertificate")
    @ResponseWrapper(localName = "editCertificateResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.EditCertificateResponse")
    public void editCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        Certificates arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuditActions", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetAuditActions")
    @ResponseWrapper(localName = "getAuditActionsResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetAuditActionsResponse")
    public List<String> getAuditActions();

    /**
     * 
     * @param franchise
     * @param receiveEnable
     * @param documentType
     * @param documentNumber
     * @param validDate
     * @param accountType
     * @param counter
     * @param micro2
     * @param alias
     * @param state
     * @param micro1
     * @param international
     * @param email
     * @param cardNumber
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFirstCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddFirstCard")
    @ResponseWrapper(localName = "addFirstCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddFirstCardResponse")
    public Response addFirstCard(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "documentType", targetNamespace = "")
        String documentType,
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "cardNumber", targetNamespace = "")
        String cardNumber,
        @WebParam(name = "counter", targetNamespace = "")
        String counter,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "validDate", targetNamespace = "")
        XMLGregorianCalendar validDate,
        @WebParam(name = "franchise", targetNamespace = "")
        String franchise,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "micro1", targetNamespace = "")
        String micro1,
        @WebParam(name = "micro2", targetNamespace = "")
        String micro2,
        @WebParam(name = "international", targetNamespace = "")
        boolean international,
        @WebParam(name = "accountType", targetNamespace = "")
        String accountType,
        @WebParam(name = "receiveEnable", targetNamespace = "")
        boolean receiveEnable);

    /**
     * 
     * @param endDate
     * @param action
     * @param startDate
     * @return
     *     returns java.util.List<com.pharos.credibanco.checkout.ws.Audit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAudit", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetAudit")
    @ResponseWrapper(localName = "getAuditResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetAuditResponse")
    public List<Audit> getAudit(
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "action", targetNamespace = "")
        String action);

    /**
     * 
     * @param confirmNewPassword
     * @param lastName
     * @param secondLastName
     * @param country
     * @param enableQ
     * @param address
     * @param documentType
     * @param city
     * @param documentNumber
     * @param expDocumentDate
     * @param newPassword
     * @param firstName
     * @param password
     * @param cellphone
     * @param email
     * @param secondName
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserData", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateUserData")
    @ResponseWrapper(localName = "updateUserDataResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateUserDataResponse")
    public Response updateUserData(
        @WebParam(name = "documentType", targetNamespace = "")
        String documentType,
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "secondName", targetNamespace = "")
        String secondName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "secondLastName", targetNamespace = "")
        String secondLastName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword,
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "cellphone", targetNamespace = "")
        String cellphone,
        @WebParam(name = "enableQ", targetNamespace = "")
        String enableQ,
        @WebParam(name = "expDocumentDate", targetNamespace = "")
        String expDocumentDate);

    /**
     * 
     * @param auditoria
     */
    @WebMethod
    @RequestWrapper(localName = "addAudit", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddAudit")
    @ResponseWrapper(localName = "addAuditResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddAuditResponse")
    public void addAudit(
        @WebParam(name = "auditoria", targetNamespace = "")
        Audit auditoria);

    /**
     * 
     * @param session
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserSession", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteUserSession")
    @ResponseWrapper(localName = "deleteUserSessionResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteUserSessionResponse")
    public void deleteUserSession(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "sendOTPEmail", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendOTPEmail")
    @ResponseWrapper(localName = "sendOTPEmailResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendOTPEmailResponse")
    public void sendOTPEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createCertificate", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateCertificate")
    @ResponseWrapper(localName = "createCertificateResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateCertificateResponse")
    public void createCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        Certificates arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param commerceName
     * @param certFile
     * @param commerceTerminalCode
     * @param commerceCode
     * @param certificateName
     * @param certificatePassword
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editCommerce", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.EditCommerce")
    @ResponseWrapper(localName = "editCommerceResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.EditCommerceResponse")
    public Response editCommerce(
        @WebParam(name = "commerceCode", targetNamespace = "")
        String commerceCode,
        @WebParam(name = "certificateName", targetNamespace = "")
        String certificateName,
        @WebParam(name = "commerceName", targetNamespace = "")
        String commerceName,
        @WebParam(name = "certificatePassword", targetNamespace = "")
        String certificatePassword,
        @WebParam(name = "commerceTerminalCode", targetNamespace = "")
        String commerceTerminalCode,
        @WebParam(name = "certFile", targetNamespace = "")
        byte[] certFile);

    /**
     * 
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "sendOTPLoginEmail", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendOTPLoginEmail")
    @ResponseWrapper(localName = "sendOTPLoginEmailResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SendOTPLoginEmailResponse")
    public void sendOTPLoginEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param user
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CompleteUser")
    @ResponseWrapper(localName = "completeUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CompleteUserResponse")
    public Response completeUser(
        @WebParam(name = "User", targetNamespace = "")
        User user);

    /**
     * 
     * @param documentNumber
     * @param auditoria
     * @return
     *     returns java.util.List<com.pharos.credibanco.checkout.ws.UserCard>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCards", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUserCards")
    @ResponseWrapper(localName = "getUserCardsResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUserCardsResponse")
    public List<UserCard> getUserCards(
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "auditoria", targetNamespace = "")
        String auditoria);

    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AuthenticateUser")
    @ResponseWrapper(localName = "authenticateUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AuthenticateUserResponse")
    public Response authenticateUser(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.pharos.credibanco.checkout.ws.RestoreSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRestoreSession", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetRestoreSession")
    @ResponseWrapper(localName = "getRestoreSessionResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetRestoreSessionResponse")
    public RestoreSession getRestoreSession(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param docNumber
     * @return
     *     returns com.pharos.credibanco.checkout.ws.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByDoc", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUserByDoc")
    @ResponseWrapper(localName = "getUserByDocResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUserByDocResponse")
    public User getUserByDoc(
        @WebParam(name = "docNumber", targetNamespace = "")
        String docNumber);

    /**
     * 
     * @param uniqueCode
     * @param terminalCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommerceApiToken", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCommerceApiToken")
    @ResponseWrapper(localName = "getCommerceApiTokenResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCommerceApiTokenResponse")
    public String getCommerceApiToken(
        @WebParam(name = "uniqueCode", targetNamespace = "")
        String uniqueCode,
        @WebParam(name = "terminalCode", targetNamespace = "")
        String terminalCode);

    /**
     * 
     * @param franchise
     * @param quotas
     * @param xml
     * @param validDate
     * @param alias
     * @param cardNumber
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.PayResponse")
    public Response pay(
        @WebParam(name = "xml", targetNamespace = "")
        String xml,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "quotas", targetNamespace = "")
        String quotas,
        @WebParam(name = "cardNumber", targetNamespace = "")
        String cardNumber,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "validDate", targetNamespace = "")
        String validDate,
        @WebParam(name = "franchise", targetNamespace = "")
        String franchise);

    /**
     * 
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setOTPLogin", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetOTPLogin")
    @ResponseWrapper(localName = "setOTPLoginResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetOTPLoginResponse")
    public Response setOTPLogin(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param uniqueCode
     * @param terminalCode
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Certificates
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCertificateByCodCommerce", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.FindCertificateByCodCommerce")
    @ResponseWrapper(localName = "findCertificateByCodCommerceResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.FindCertificateByCodCommerceResponse")
    public Certificates findCertificateByCodCommerce(
        @WebParam(name = "uniqueCode", targetNamespace = "")
        String uniqueCode,
        @WebParam(name = "terminalCode", targetNamespace = "")
        String terminalCode);

    /**
     * 
     * @param commerceCode
     * @param terminalCode
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Certificates
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommerce", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCommerce")
    @ResponseWrapper(localName = "getCommerceResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCommerceResponse")
    public Certificates getCommerce(
        @WebParam(name = "commerceCode", targetNamespace = "")
        String commerceCode,
        @WebParam(name = "terminalCode", targetNamespace = "")
        String terminalCode);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCiudadesDane", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCiudadesDane")
    @ResponseWrapper(localName = "getCiudadesDaneResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetCiudadesDaneResponse")
    public List<String> getCiudadesDane();

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCertificate", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCertificate")
    @ResponseWrapper(localName = "deleteCertificateResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCertificateResponse")
    public void deleteCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param documentNumber
     * @param id
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCard2Receive", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetCard2Receive")
    @ResponseWrapper(localName = "setCard2ReceiveResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetCard2ReceiveResponse")
    public Response setCard2Receive(
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param franchise
     * @param receiveEnable
     * @param documentType
     * @param documentNumber
     * @param validDate
     * @param accountType
     * @param counter
     * @param micro2
     * @param alias
     * @param state
     * @param micro1
     * @param international
     * @param email
     * @param cardNumber
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddCard")
    @ResponseWrapper(localName = "addCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.AddCardResponse")
    public Response addCard(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "documentType", targetNamespace = "")
        String documentType,
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "cardNumber", targetNamespace = "")
        String cardNumber,
        @WebParam(name = "counter", targetNamespace = "")
        String counter,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "validDate", targetNamespace = "")
        XMLGregorianCalendar validDate,
        @WebParam(name = "franchise", targetNamespace = "")
        String franchise,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "micro1", targetNamespace = "")
        String micro1,
        @WebParam(name = "micro2", targetNamespace = "")
        String micro2,
        @WebParam(name = "international", targetNamespace = "")
        boolean international,
        @WebParam(name = "accountType", targetNamespace = "")
        String accountType,
        @WebParam(name = "receiveEnable", targetNamespace = "")
        boolean receiveEnable);

    /**
     * 
     * @param otp
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateOTP", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateOTP")
    @ResponseWrapper(localName = "validateOTPResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateOTPResponse")
    public Response validateOTP(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "otp", targetNamespace = "")
        String otp);

    /**
     * 
     * @param documentNumber
     * @param id
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setFavoriteCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetFavoriteCard")
    @ResponseWrapper(localName = "setFavoriteCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetFavoriteCardResponse")
    public Response setFavoriteCard(
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetUserResponse")
    public User getUser(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param posPago
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postPago", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.PostPago")
    @ResponseWrapper(localName = "postPagoResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.PostPagoResponse")
    public Response postPago(
        @WebParam(name = "posPago", targetNamespace = "")
        PosPago posPago);

    /**
     * 
     * @param otp
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateOTPLogin", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateOTPLogin")
    @ResponseWrapper(localName = "validateOTPLoginResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateOTPLoginResponse")
    public Response validateOTPLogin(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "otp", targetNamespace = "")
        String otp);

    /**
     * 
     * @param alias
     * @param id
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCardAlias", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateCardAlias")
    @ResponseWrapper(localName = "updateCardAliasResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateCardAliasResponse")
    public Response updateCardAlias(
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "alias", targetNamespace = "")
        String alias);

    /**
     * 
     * @param range
     * @return
     *     returns com.pharos.credibanco.checkout.ws.BinesRange
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFranchiseByBinRange", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFranchiseByBinRange")
    @ResponseWrapper(localName = "getFranchiseByBinRangeResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFranchiseByBinRangeResponse")
    public BinesRange getFranchiseByBinRange(
        @WebParam(name = "range", targetNamespace = "")
        long range);

    /**
     * 
     * @param alias
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCard")
    @ResponseWrapper(localName = "deleteCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.DeleteCardResponse")
    public Response deleteCard(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "alias", targetNamespace = "")
        String alias);

    /**
     * 
     * @param documentNumber
     * @param auditoria
     * @return
     *     returns com.pharos.credibanco.checkout.ws.UserCard
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFavoriteCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFavoriteCard")
    @ResponseWrapper(localName = "getFavoriteCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFavoriteCardResponse")
    public UserCard getFavoriteCard(
        @WebParam(name = "documentNumber", targetNamespace = "")
        String documentNumber,
        @WebParam(name = "auditoria", targetNamespace = "")
        String auditoria);

    /**
     * 
     * @param user
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateUserResponse")
    public Response createUser(
        @WebParam(name = "User", targetNamespace = "")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<com.pharos.credibanco.checkout.ws.Faq>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFaqList", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFaqList")
    @ResponseWrapper(localName = "getFaqListResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetFaqListResponse")
    public List<Faq> getFaqList();

    /**
     * 
     * @param user
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidateUserResponse")
    public Response validateUser(
        @WebParam(name = "User", targetNamespace = "")
        User user);

    /**
     * 
     * @param confirmNewPassword
     * @param oldPassword
     * @param newPassword
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ChangePasswordResponse")
    public Response changePassword(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "oldPassword", targetNamespace = "")
        String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword);

    /**
     * 
     * @param session
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validSession", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidSession")
    @ResponseWrapper(localName = "validSessionResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ValidSessionResponse")
    public Response validSession(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param nombre
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Parameter
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParameterByName", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetParameterByName")
    @ResponseWrapper(localName = "getParameterByNameResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.GetParameterByNameResponse")
    public Parameter getParameterByName(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setOTP", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetOTP")
    @ResponseWrapper(localName = "setOTPResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.SetOTPResponse")
    public Response setOTP(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param confirmNewPassword
     * @param newPassword
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restoreLinkPassword", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.RestoreLinkPassword")
    @ResponseWrapper(localName = "restoreLinkPasswordResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.RestoreLinkPasswordResponse")
    public Response restoreLinkPassword(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword);

    /**
     * 
     * @param session
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "activateuser", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.Activateuser")
    @ResponseWrapper(localName = "activateuserResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ActivateuserResponse")
    public void activateuser(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param session
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "activateSession", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ActivateSession")
    @ResponseWrapper(localName = "activateSessionResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ActivateSessionResponse")
    public void activateSession(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param commerceName
     * @param certFile
     * @param commerceTerminalCode
     * @param commerceCode
     * @param certificateName
     * @param certificatePassword
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCommerce", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateCommerce")
    @ResponseWrapper(localName = "createCommerceResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.CreateCommerceResponse")
    public Response createCommerce(
        @WebParam(name = "commerceCode", targetNamespace = "")
        String commerceCode,
        @WebParam(name = "certificateName", targetNamespace = "")
        String certificateName,
        @WebParam(name = "commerceName", targetNamespace = "")
        String commerceName,
        @WebParam(name = "certificatePassword", targetNamespace = "")
        String certificatePassword,
        @WebParam(name = "commerceTerminalCode", targetNamespace = "")
        String commerceTerminalCode,
        @WebParam(name = "certFile", targetNamespace = "")
        byte[] certFile);

    /**
     * 
     * @param user
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTrx", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateTrx")
    @ResponseWrapper(localName = "updateTrxResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.UpdateTrxResponse")
    public Response updateTrx(
        @WebParam(name = "User", targetNamespace = "")
        User user);

    /**
     * 
     * @param idCard
     * @param email
     * @return
     *     returns com.pharos.credibanco.checkout.ws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activateCard", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ActivateCard")
    @ResponseWrapper(localName = "activateCardResponse", targetNamespace = "http://ws.checkout.credibanco.pharos.com/", className = "com.pharos.credibanco.checkout.ws.ActivateCardResponse")
    public Response activateCard(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "idCard", targetNamespace = "")
        long idCard);

}
